### ISSUE TITLE
License for this repo?

### ISSUE THREAD

**Issue by jasnow** [iridakos/lofocats_api#1]
Can we add a license to this repo so I know the conditions to contribute?

Example: https://github.com/atlrug/atlrug4/blob/master/MIT-LICENSE.txt

More information at: http://opensource.org/licenses

Thanks....

**Comment by iridakos** [comment]
Added LICENSE.md (MIT)

**Comment by jasnow** [comment]
Thanks

**Comment by iridakos** [comment]
No prob. I'm not very familiar with the licensing stuff. Hope it's good.
